/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Dimension;
import javax.swing.JButton;

/**
 *
 * @author dtame
 */
public class WorshipPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorshipPanel
     */
    public WorshipPanel() {
        initComponents();
        
        setMaximumSize(new Dimension(0, 400));        
        searchField.setMaximumSize(new Dimension(500, 50));
        songScrollPane.setPreferredSize(new Dimension(650, 400));
        buttonPanel.setPreferredSize(new Dimension(120,150));
        
        JButton btn1 = new JButton("Add song");
        JButton btn2 = new JButton("Remove song");
        
        buttonPanel.add(btn1);
        buttonPanel.add(btn2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        songScrollPane = new javax.swing.JScrollPane();
        songList = new javax.swing.JList<>();
        buttonPanel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Worship songs"));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        add(searchField);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        songList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        songScrollPane.setViewportView(songList);

        jPanel1.add(songScrollPane);

        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.add(buttonPanel);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField searchField;
    private javax.swing.JList<String> songList;
    private javax.swing.JScrollPane songScrollPane;
    // End of variables declaration//GEN-END:variables
}
